#ifndef KEYCODES_H
#define KEYCODES_H

typedef unsigned char small;
typedef unsigned short ushort;

const ushort KEY_LEFT_ARROW = 63495;
const ushort KEY_RIGHT_ARROW = 63496;
const ushort KEY_UP_ARROW = 63497;
const ushort KEY_DOWN_ARROW = 63498;
const ushort KEY_LEFT_SOFTKEY = 63554;
const ushort KEY_RIGHT_SOFTKEY = 63555;
const ushort KEY_OK = 63557;
const ushort KEY_DIAL = 63586;
const small KEY_ENTER = 13;
const small KEY_BACKSPACE = 8;

const small KEY_CTRL_A = 1;
const small KEY_CTRL_B = 2;
const small KEY_CTRL_C = 3;
const small KEY_CTRL_D = 4;
const small KEY_CTRL_E = 5;
const small KEY_CTRL_F = 6;
const small KEY_CTRL_G = 7;
const small KEY_CTRL_H = 8;
const small KEY_CTRL_I = 9;
const small KEY_CTRL_J = 10;
const small KEY_CTRL_K = 11;
const small KEY_CTRL_L = 12;
const small KEY_CTRL_M = 13;
const small KEY_CTRL_N = 14;
const small KEY_CTRL_O = 15;
const small KEY_CTRL_P = 16;
const small KEY_CTRL_Q = 17;
const small KEY_CTRL_R = 18;
const small KEY_CTRL_S = 19;
const small KEY_CTRL_T = 20;
const small KEY_CTRL_U = 21;
const small KEY_CTRL_V = 22;
const small KEY_CTRL_W = 23;
const small KEY_CTRL_X = 24;
const small KEY_CTRL_Y = 25;
const small KEY_CTRL_Z = 26;

const small KEY_SPACE = 32;
const small KEY_EXCLAMATION_MARK = 33;
const small KEY_HASH = 35;
const small KEY_AMPERSAND = 38;
const small KEY_APOSTROF = 39;
const small KEY_LEFT_BRACKET = 40;
const small KEY_RIGHT_BRACKET = 41;
const small KEY_STAR = 42;
const small KEY_PLUS = 43;
const small KEY_COMMA = 44;
const small KEY_MINUS = 45;
const small KEY_DOT = 46;
const small KEY_SLASH = 47;
const small KEY_0 = 48;
const small KEY_1 = 49;
const small KEY_2 = 50;
const small KEY_3 = 51;
const small KEY_4 = 52;
const small KEY_5 = 53;
const small KEY_6 = 54;
const small KEY_7 = 55;
const small KEY_8 = 56;
const small KEY_9 = 57;
const small KEY_COLON = 58;
const small KEY_SEMICOLON = 59;
const small KEY_EQUALS = 61;
const small KEY_QUESTION_MARK = 63;
const small KEY_AT = 64;

const small KEY_SHIFT_A = 65;
const small KEY_SHIFT_B = 66;
const small KEY_SHIFT_C = 67;
const small KEY_SHIFT_D = 68;
const small KEY_SHIFT_E = 69;
const small KEY_SHIFT_F = 70;
const small KEY_SHIFT_G = 71;
const small KEY_SHIFT_H = 72;
const small KEY_SHIFT_I = 73;
const small KEY_SHIFT_J = 74;
const small KEY_SHIFT_K = 75;
const small KEY_SHIFT_L = 76;
const small KEY_SHIFT_M = 77;
const small KEY_SHIFT_N = 78;
const small KEY_SHIFT_O = 79;
const small KEY_SHIFT_P = 80;
const small KEY_SHIFT_Q = 81;
const small KEY_SHIFT_R = 82;
const small KEY_SHIFT_S = 83;
const small KEY_SHIFT_T = 84;
const small KEY_SHIFT_U = 85;
const small KEY_SHIFT_V = 86;
const small KEY_SHIFT_W = 87;
const small KEY_SHIFT_X = 88;
const small KEY_SHIFT_Y = 89;
const small KEY_SHIFT_Z = 90;

const small KEY_A = 97;
const small KEY_B = 98;
const small KEY_C = 99;
const small KEY_D = 100;
const small KEY_E = 101;
const small KEY_F = 102;
const small KEY_G = 103;
const small KEY_H = 104;
const small KEY_I = 105;
const small KEY_J = 106;
const small KEY_K = 107;
const small KEY_L = 108;
const small KEY_M = 109;
const small KEY_N = 110;
const small KEY_O = 111;
const small KEY_P = 112;
const small KEY_Q = 113;
const small KEY_R = 114;
const small KEY_S = 115;
const small KEY_T = 116;
const small KEY_U = 117;
const small KEY_V = 118;
const small KEY_W = 119;
const small KEY_X = 120;
const small KEY_Y = 121;
const small KEY_Z = 122;

#endif // KEYCODES_H
